param(
  [switch]$NoCommit,
  [switch]$NoPush
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Say($text) {
  Write-Host "[Hinata OSS] $text" -ForegroundColor Cyan
}

function Write-B64($relativePath, $encoded) {
  $target = Join-Path (Get-Location) $relativePath
  $parent = Split-Path -Parent $target
  if ($parent -and -not (Test-Path $parent)) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
  }
  [System.IO.File]::WriteAllBytes($target, [System.Convert]::FromBase64String($encoded))
}

Say "Checking repository..."
if (-not (Test-Path ".git")) {
  throw "Run this script from the root of your cloned hinata-bot repository."
}
if (-not (Test-Path "package.json")) {
  throw "package.json was not found. Make sure VS Code is opened at the hinata-bot root."
}

$remote = (git remote get-url origin 2>$null)
if ($LASTEXITCODE -ne 0 -or $remote -notmatch "ajaydudhaml01-arch/hinata-bot") {
  throw "This does not look like ajaydudhaml01-arch/hinata-bot. Origin: $remote"
}

$dirty = @(git status --porcelain)
if ($dirty.Count -gt 0) {
  Write-Host ""
  Write-Host "Your repo already has uncommitted changes:" -ForegroundColor Yellow
  $dirty | ForEach-Object { Write-Host "  $_" }
  Write-Host ""
  throw "Commit/stash those changes first, then run the upgrade again so nothing gets overwritten."
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path ".oss-backup" $stamp
New-Item -ItemType Directory -Force -Path $backup | Out-Null

foreach ($p in @("README.md", "package.json", ".gitignore", "config.json", "data/levels.json")) {
  if (Test-Path $p) {
    $dest = Join-Path $backup $p
    $destParent = Split-Path -Parent $dest
    if ($destParent -and -not (Test-Path $destParent)) {
      New-Item -ItemType Directory -Force -Path $destParent | Out-Null
    }
    Copy-Item $p $dest -Force
  }
}
Say "Local backup created at $backup"

Say "Writing OSS files..."
Write-B64 "README.md" "IyBIaW5hdGEKClshW0NJXShodHRwczovL2dpdGh1Yi5jb20vYWpheWR1ZGhhbWwwMS1hcmNoL2hpbmF0YS1ib3QvYWN0aW9ucy93b3JrZmxvd3MvY2kueW1sL2JhZGdlLnN2ZyldKGh0dHBzOi8vZ2l0aHViLmNvbS9hamF5ZHVkaGFtbDAxLWFyY2gvaGluYXRhLWJvdC9hY3Rpb25zL3dvcmtmbG93cy9jaS55bWwpClshW0xpY2Vuc2U6IE1JVF0oaHR0cHM6Ly9pbWcuc2hpZWxkcy5pby9iYWRnZS9MaWNlbnNlLU1JVC15ZWxsb3cuc3ZnKV0oTElDRU5TRSkKIVtOb2RlLmpzXShodHRwczovL2ltZy5zaGllbGRzLmlvL2JhZGdlL05vZGUuanMtMTguMTglMkItYnJpZ2h0Z3JlZW4pCgoqKkhpbmF0YSoqIGlzIGEgbW9kdWxhciwgb3Blbi1zb3VyY2UgRGlzY29yZCBib3QgYnVpbHQgd2l0aCBEaXNjb3JkLmpzLiBJdCBjb21iaW5lcyBtb2RlcmF0aW9uLCB0aWNrZXRzLCBsZXZlbGluZywgZHluYW1pYyB2b2ljZSBjaGFubmVscywgc2VsZi1yb2xlcywgd2VsY29tZS9mYXJld2VsbCBhdXRvbWF0aW9uLCBwb2xscywgc2VydmVyIHV0aWxpdGllcywgYW5kIGEgbGlnaHR3ZWlnaHQgaGVhbHRoIGVuZHBvaW50IGZvciBjbG91ZCBob3N0aW5nLgoKVGhlIGdvYWwgaXMgdG8gcHJvdmlkZSBhIGNsZWFuIGJhc2UgdGhhdCBjb21tdW5pdHkgb3duZXJzIGFuZCBkZXZlbG9wZXJzIGNhbiBjb25maWd1cmUsIGV4dGVuZCwgYW5kIHNlbGYtaG9zdC4KCiMjIEZlYXR1cmVzCgotICoqTW9kZXJhdGlvbioqIOKAlCBraWNrLCBiYW4sIHRpbWVvdXQsIHB1cmdlLCB3YXJuaW5ncywgbG9nZ2luZwotICoqQXV0by1tb2RlcmF0aW9uKiog4oCUIGludml0ZSBmaWx0ZXJpbmcsIGJsb2NrZWQtd29yZCBmaWx0ZXJpbmcsIGFudGktc3BhbSBwcm90ZWN0aW9uCi0gKipTdXBwb3J0IHRpY2tldHMqKiDigJQgcHJpdmF0ZSB0aWNrZXQgY2hhbm5lbCBjcmVhdGlvbiBhbmQgc3RhZmYgYWNjZXNzCi0gKipMZXZlbGluZyoqIOKAlCBYUCwgbGV2ZWxzLCBsZWFkZXJib2FyZCBzdXBwb3J0LCBtaWxlc3RvbmUgcm9sZXMKLSAqKkR5bmFtaWMgdm9pY2UgY2hhbm5lbHMqKiDigJQgam9pbi10by1jcmVhdGUgdm9pY2Ugcm9vbXMgdGhhdCBjbGVhbiB0aGVtc2VsdmVzIHVwCi0gKipTZWxmIHJvbGVzKiog4oCUIGJ1dHRvbi1iYXNlZCByb2xlIGFzc2lnbm1lbnQKLSAqKkNvbW11bml0eSB0b29scyoqIOKAlCBwb2xscywgbWVtZXMsIHVzZXIgaW5mbywgc2VydmVyIGluZm8sIGxhdGVuY3kgY2hlY2tzCi0gKipNZW1iZXIgYXV0b21hdGlvbioqIOKAlCB3ZWxjb21lL2ZhcmV3ZWxsIG1lc3NhZ2VzIGFuZCBvcHRpb25hbCBtZW1iZXIgcm9sZQotICoqQ2xvdWQtZnJpZW5kbHkqKiDigJQgbGlnaHR3ZWlnaHQgSFRUUCBoZWFsdGggcGFnZSBmb3IgUmVuZGVyL0tveWViLXN0eWxlIGhvc3RpbmcKLSAqKk1vZHVsYXIgc3RydWN0dXJlKiog4oCUIGNvbW1hbmRzLCBldmVudHMsIGFuZCBoYW5kbGVycyBhcmUgc2VwYXJhdGVkIHVuZGVyIGBzcmMvYAoKIyMgUmVxdWlyZW1lbnRzCgotIE5vZGUuanMgKioxOC4xOCBvciBuZXdlcioqCi0gbnBtCi0gQSBEaXNjb3JkIGFwcGxpY2F0aW9uIGFuZCBib3QgdG9rZW4KLSBBIERpc2NvcmQgc2VydmVyIHdoZXJlIHlvdSBjYW4gbWFuYWdlIHRoZSBib3QKCiMjIFF1aWNrIHN0YXJ0CgpgYGBiYXNoCmdpdCBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vYWpheWR1ZGhhbWwwMS1hcmNoL2hpbmF0YS1ib3QuZ2l0CmNkIGhpbmF0YS1ib3QKbnBtIGluc3RhbGwKYGBgCgpDcmVhdGUgeW91ciBsb2NhbCBlbnZpcm9ubWVudCBmaWxlOgoKYGBgcG93ZXJzaGVsbApDb3B5LUl0ZW0gLmVudi5leGFtcGxlIC5lbnYKYGBgCgpPbiBtYWNPUy9MaW51eDoKCmBgYGJhc2gKY3AgLmVudi5leGFtcGxlIC5lbnYKYGBgCgpGaWxsIGluOgoKYGBgZW52CkRJU0NPUkRfVE9LRU49eW91cl9ib3RfdG9rZW5faGVyZQpDTElFTlRfSUQ9eW91cl9kaXNjb3JkX2FwcGxpY2F0aW9uX2NsaWVudF9pZApHVUlMRF9JRD15b3VyX2RldmVsb3BtZW50X3NlcnZlcl9pZApgYGAKCkNyZWF0ZSB5b3VyIGxvY2FsIGJvdCBjb25maWd1cmF0aW9uOgoKYGBgcG93ZXJzaGVsbApDb3B5LUl0ZW0gY29uZmlnLmV4YW1wbGUuanNvbiBjb25maWcuanNvbgpgYGAKClRoZW4gZWRpdCBgY29uZmlnLmpzb25gIGZvciB5b3VyIHNlcnZlciBhbmQgc3RhcnQgSGluYXRhOgoKYGBgYmFzaApucG0gc3RhcnQKYGBgCgo+IGBjb25maWcuanNvbmAsIGAuZW52YCwgYW5kIHJ1bnRpbWUgSlNPTiBkYXRhIGFyZSBpbnRlbnRpb25hbGx5IGlnbm9yZWQgYnkgR2l0IHNvIHlvdXIgc2VydmVyLXNwZWNpZmljIGNvbmZpZ3VyYXRpb24gYW5kIGdlbmVyYXRlZCBkYXRhIGRvIG5vdCBiZWNvbWUgcGFydCBvZiB0aGUgcHVibGljIHJlcG9zaXRvcnkuCgojIyBEaXNjb3JkIHNldHVwCgpJbiB0aGUgRGlzY29yZCBEZXZlbG9wZXIgUG9ydGFsOgoKMS4gQ3JlYXRlIGFuIGFwcGxpY2F0aW9uIGFuZCBib3QuCjIuIEVuYWJsZSB0aGUgaW50ZW50cyByZXF1aXJlZCBieSB0aGUgZmVhdHVyZXMgeW91IHVzZToKICAgLSBTZXJ2ZXIgTWVtYmVycyBJbnRlbnQKICAgLSBNZXNzYWdlIENvbnRlbnQgSW50ZW50CiAgIC0gUHJlc2VuY2UgSW50ZW50IGlmIG5lZWRlZCBieSB5b3VyIGRlcGxveW1lbnQvZmVhdHVyZXMKMy4gSW52aXRlIHRoZSBib3Qgd2l0aCB0aGUgYGJvdGAgYW5kIGBhcHBsaWNhdGlvbnMuY29tbWFuZHNgIHNjb3Blcy4KNC4gR3JhbnQgb25seSB0aGUgcGVybWlzc2lvbnMgcmVxdWlyZWQgYnkgdGhlIGZlYXR1cmVzIHlvdSBlbmFibGUuCgpBdm9pZCBncmFudGluZyBgQWRtaW5pc3RyYXRvcmAgdW5sZXNzIHlvdSB1bmRlcnN0YW5kIGFuZCBleHBsaWNpdGx5IG5lZWQgdGhlIGFkZGl0aW9uYWwgYWNjZXNzLgoKIyMgQ29tbWFuZHMKCkhpbmF0YSBjdXJyZW50bHkgaW5jbHVkZXMgY29tbWFuZHMgYWNyb3NzIHRoZXNlIGdyb3VwczoKCnwgR3JvdXAgfCBFeGFtcGxlcyB8CnwgLS0tIHwgLS0tIHwKfCBVdGlsaXR5IHwgYC9oZWxwYCwgYC9waW5nYCwgYC9zZXJ2ZXJpbmZvYCwgYC91c2VyaW5mb2AsIGAvcmFua2AgfAp8IE1vZGVyYXRpb24gfCBgL2tpY2tgLCBgL2JhbmAsIGAvdGltZW91dGAsIGAvcHVyZ2VgLCBgL3dhcm5gIHwKfCBDb21tdW5pdHkgfCBgL3BvbGxgLCBgL21lbWVgIHwKfCBUaWNrZXRzIHwgYC90aWNrZXQgc2V0dXBgIHwKfCBSb2xlcyB8IGAvcm9sZXMgc2V0dXBgIHwKCkNvbW1hbmQgYXZhaWxhYmlsaXR5IGNhbiBldm9sdmUgYXMgdGhlIHByb2plY3QgaXMgdXBkYXRlZC4gU2VlIGBzcmMvY29tbWFuZHMvYCBmb3IgdGhlIHNvdXJjZSBvZiB0cnV0aC4KCiMjIENvbmZpZ3VyYXRpb24KCmBjb25maWcuZXhhbXBsZS5qc29uYCBjb250YWlucyB0aGUgcmV1c2FibGUgY29uZmlndXJhdGlvbiB0ZW1wbGF0ZS4KCkltcG9ydGFudCBzZXR0aW5ncyBpbmNsdWRlOgoKLSBgd2VsY29tZUNoYW5uZWxJZGAKLSBgZmFyZXdlbGxDaGFubmVsSWRgCi0gYHdlbGNvbWVSb2xlTmFtZWAKLSBgdGlja2V0Q2F0ZWdvcnlJZGAKLSBgdGlja2V0U3RhZmZSb2xlSWRgCi0gYGxvZ0NoYW5uZWxJZGAKLSBgam9pblRvQ3JlYXRlQ2hhbm5lbElkYAotIGBibG9ja2VkV29yZHNgCi0gYGxldmVsUm9sZXNgCi0gYG1lbWJlckNvdW50Q2hhbm5lbElkYAoKTGVhdmUgb3B0aW9uYWwgSURzIGFzIGVtcHR5IHN0cmluZ3Mgd2hlbiBhIGZlYXR1cmUgaXMgbm90IGNvbmZpZ3VyZWQuCgojIyBQcm9qZWN0IHN0cnVjdHVyZQoKYGBgdGV4dApoaW5hdGEtYm90LwrilJzilIDilIAgaW5kZXguanMK4pSc4pSA4pSAIHNyYy8K4pSCICAg4pSc4pSA4pSAIGNvbW1hbmRzLwrilIIgICDilJzilIDilIAgZXZlbnRzLwrilIIgICDilJTilIDilIAgaGFuZGxlcnMvCuKUnOKUgOKUgCBkYXRhLyAgICAgICAgICAgICAgICAgIyBsb2NhbCBydW50aW1lIGRhdGE7IGNvbnRlbnRzIGFyZSBpZ25vcmVkCuKUnOKUgOKUgCB0ZXN0cy8K4pSc4pSA4pSAIGNvbmZpZy5leGFtcGxlLmpzb24K4pSc4pSA4pSAIC5lbnYuZXhhbXBsZQrilJTilIDilIAgLmdpdGh1Yi8KYGBgCgpTZWUgW2RvY3MvQVJDSElURUNUVVJFLm1kXShkb2NzL0FSQ0hJVEVDVFVSRS5tZCkgZm9yIGEgY29udHJpYnV0b3Itb3JpZW50ZWQgb3ZlcnZpZXcuCgojIyBEZXZlbG9wbWVudAoKQ2hlY2sgc3ludGF4OgoKYGBgYmFzaApucG0gcnVuIGNoZWNrCmBgYAoKUnVuIHRlc3RzOgoKYGBgYmFzaApucG0gdGVzdApgYGAKClRoZSByZXBvc2l0b3J5IGluY2x1ZGVzIEdpdEh1YiBBY3Rpb25zIENJIGZvciBzdXBwb3J0ZWQgTm9kZS5qcyB2ZXJzaW9ucy4KCiMjIEhvc3RpbmcKCkhpbmF0YSBzdGFydHMgYSBsaWdodHdlaWdodCBIVFRQIHNlcnZlciBvbiBgUE9SVGAgKGRlZmF1bHQgYDgwODBgKSBpbiBhZGRpdGlvbiB0byB0aGUgRGlzY29yZCBjbGllbnQuIFRoaXMgaGVscHMgcGxhdGZvcm1zIHRoYXQgcmVxdWlyZSBhbiBIVFRQIGxpc3RlbmVyIGZvciBzZXJ2aWNlIGhlYWx0aCBjaGVja3MuCgpGb3IgcHJvZHVjdGlvbjoKCi0gc3RvcmUgc2VjcmV0cyBpbiB0aGUgaG9zdCdzIGVudmlyb25tZW50LXZhcmlhYmxlL3NlY3JldCBtYW5hZ2VyCi0gbmV2ZXIgY29tbWl0IGAuZW52YAotIHVzZSBwZXJzaXN0ZW50IHN0b3JhZ2UgaWYgeW91IG5lZWQgbG9jYWwgSlNPTiBkYXRhIHRvIHN1cnZpdmUgcmVzdGFydHMKLSBjb25zaWRlciBhIGRhdGFiYXNlIGZvciBsYXJnZXIgb3IgbXVsdGktaW5zdGFuY2UgZGVwbG95bWVudHMKCiMjIERhdGEgYW5kIHByaXZhY3kKClRoZSBjdXJyZW50IGxldmVsaW5nL3dhcm5pbmcgc3lzdGVtcyBtYXkgc3RvcmUgRGlzY29yZCBpZGVudGlmaWVycyBhbmQgYm90LWdlbmVyYXRlZCBzdGF0ZSBpbiBsb2NhbCBKU09OIGZpbGVzLiBSdW50aW1lIGRhdGEgdW5kZXIgYGRhdGEvYCBpcyBpbnRlbnRpb25hbGx5IGV4Y2x1ZGVkIGZyb20gR2l0LgoKU2VydmVyIG93bmVycyBhcmUgcmVzcG9uc2libGUgZm9yIGluZm9ybWluZyB0aGVpciB1c2VycyBhYm91dCBhbnkgZGF0YSB0aGV5IGNvbGxlY3QgYW5kIGZvciBjb21wbHlpbmcgd2l0aCBhcHBsaWNhYmxlIERpc2NvcmQgcG9saWNpZXMgYW5kIHByaXZhY3kgcmVxdWlyZW1lbnRzLgoKIyMgU2VjdXJpdHkKCk5ldmVyIHBvc3QgeW91ciBEaXNjb3JkIGJvdCB0b2tlbiwgYC5lbnZgIGZpbGUsIHByaXZhdGUgY3JlZGVudGlhbHMsIG9yIHNlbnNpdGl2ZSBzZXJ2ZXIgZGF0YSBpbiBhbiBpc3N1ZS4KCkZvciB2dWxuZXJhYmlsaXR5IHJlcG9ydGluZywgcmVhZCBbU0VDVVJJVFkubWRdKFNFQ1VSSVRZLm1kKS4KCiMjIENvbnRyaWJ1dGluZwoKQ29udHJpYnV0aW9ucyBhcmUgd2VsY29tZS4gUGxlYXNlIHJlYWQgW0NPTlRSSUJVVElORy5tZF0oQ09OVFJJQlVUSU5HLm1kKSBiZWZvcmUgb3BlbmluZyBhIHB1bGwgcmVxdWVzdC4KClVzZWZ1bCBwbGFjZXMgdG8gc3RhcnQ6CgotIGJ1ZyBmaXhlcwotIHRlc3RzCi0gZG9jdW1lbnRhdGlvbgotIHBlci1ndWlsZCBjb25maWd1cmF0aW9uIGltcHJvdmVtZW50cwotIHBlcnNpc3RlbmNlL2RhdGFiYXNlIGFkYXB0ZXJzCi0gYWNjZXNzaWJpbGl0eSBhbmQgVVggaW1wcm92ZW1lbnRzIGZvciBpbnRlcmFjdGlvbnMKCiMjIFJvYWRtYXAKClNlZSBbUk9BRE1BUC5tZF0oUk9BRE1BUC5tZCkuCgojIyBMaWNlbnNlCgpIaW5hdGEgaXMgcmVsZWFzZWQgdW5kZXIgdGhlIFtNSVQgTGljZW5zZV0oTElDRU5TRSkuCgojIyBNYWludGFpbmVyCgpNYWludGFpbmVkIGJ5IFtBamF5IER1ZGhtYWxdKGh0dHBzOi8vZ2l0aHViLmNvbS9hamF5ZHVkaGFtbDAxLWFyY2gpLgo="
Write-B64 "LICENSE" "TUlUIExpY2Vuc2UKCkNvcHlyaWdodCAoYykgMjAyNiBBamF5IER1ZGhtYWwKClBlcm1pc3Npb24gaXMgaGVyZWJ5IGdyYW50ZWQsIGZyZWUgb2YgY2hhcmdlLCB0byBhbnkgcGVyc29uIG9idGFpbmluZyBhIGNvcHkKb2YgdGhpcyBzb2Z0d2FyZSBhbmQgYXNzb2NpYXRlZCBkb2N1bWVudGF0aW9uIGZpbGVzICh0aGUgIlNvZnR3YXJlIiksIHRvIGRlYWwKaW4gdGhlIFNvZnR3YXJlIHdpdGhvdXQgcmVzdHJpY3Rpb24sIGluY2x1ZGluZyB3aXRob3V0IGxpbWl0YXRpb24gdGhlIHJpZ2h0cwp0byB1c2UsIGNvcHksIG1vZGlmeSwgbWVyZ2UsIHB1Ymxpc2gsIGRpc3RyaWJ1dGUsIHN1YmxpY2Vuc2UsIGFuZC9vciBzZWxsCmNvcGllcyBvZiB0aGUgU29mdHdhcmUsIGFuZCB0byBwZXJtaXQgcGVyc29ucyB0byB3aG9tIHRoZSBTb2Z0d2FyZSBpcwpmdXJuaXNoZWQgdG8gZG8gc28sIHN1YmplY3QgdG8gdGhlIGZvbGxvd2luZyBjb25kaXRpb25zOgoKVGhlIGFib3ZlIGNvcHlyaWdodCBub3RpY2UgYW5kIHRoaXMgcGVybWlzc2lvbiBub3RpY2Ugc2hhbGwgYmUgaW5jbHVkZWQgaW4gYWxsCmNvcGllcyBvciBzdWJzdGFudGlhbCBwb3J0aW9ucyBvZiB0aGUgU29mdHdhcmUuCgpUSEUgU09GVFdBUkUgSVMgUFJPVklERUQgIkFTIElTIiwgV0lUSE9VVCBXQVJSQU5UWSBPRiBBTlkgS0lORCwgRVhQUkVTUyBPUgpJTVBMSUVELCBJTkNMVURJTkcgQlVUIE5PVCBMSU1JVEVEIFRPIFRIRSBXQVJSQU5USUVTIE9GIE1FUkNIQU5UQUJJTElUWSwKRklUTkVTUyBGT1IgQSBQQVJUSUNVTEFSIFBVUlBPU0UgQU5EIE5PTklORlJJTkdFTUVOVC4gSU4gTk8gRVZFTlQgU0hBTEwgVEhFCkFVVEhPUlMgT1IgQ09QWVJJR0hUIEhPTERFUlMgQkUgTElBQkxFIEZPUiBBTlkgQ0xBSU0sIERBTUFHRVMgT1IgT1RIRVIKTElBQklMSVRZLCBXSEVUSEVSIElOIEFOIEFDVElPTiBPRiBDT05UUkFDVCwgVE9SVCBPUiBPVEhFUldJU0UsIEFSSVNJTkcgRlJPTSwKT1VUIE9GIE9SIElOIENPTk5FQ1RJT04gV0lUSCBUSEUgU09GVFdBUkUgT1IgVEhFIFVTRSBPUiBPVEhFUiBERUFMSU5HUyBJTiBUSEUKU09GVFdBUkUuCg=="
Write-B64 "package.json" "ewogICJuYW1lIjogImhpbmF0YS1kaXNjb3JkLWJvdCIsCiAgInZlcnNpb24iOiAiMS4wLjAiLAogICJkZXNjcmlwdGlvbiI6ICJBIG1vZHVsYXIgb3Blbi1zb3VyY2UgRGlzY29yZC5qcyBib3QgZm9yIG1vZGVyYXRpb24sIHRpY2tldHMsIGxldmVsaW5nLCBkeW5hbWljIHZvaWNlIGNoYW5uZWxzLCBzZWxmLXJvbGVzLCBhbmQgY29tbXVuaXR5IHV0aWxpdGllcy4iLAogICJtYWluIjogImluZGV4LmpzIiwKICAic2NyaXB0cyI6IHsKICAgICJzdGFydCI6ICJub2RlIGluZGV4LmpzIiwKICAgICJjaGVjayI6ICJub2RlIC0tY2hlY2sgaW5kZXguanMiLAogICAgInRlc3QiOiAibm9kZSAtLXRlc3QiCiAgfSwKICAia2V5d29yZHMiOiBbCiAgICAiZGlzY29yZCIsCiAgICAiZGlzY29yZC1ib3QiLAogICAgImRpc2NvcmQtanMiLAogICAgIm1vZGVyYXRpb24iLAogICAgInRpY2tldHMiLAogICAgImxldmVsaW5nIiwKICAgICJhdXRvbW9kIiwKICAgICJzZWxmLWhvc3RlZCIsCiAgICAib3Blbi1zb3VyY2UiCiAgXSwKICAiYXV0aG9yIjogIkFqYXkgRHVkaG1hbCIsCiAgImxpY2Vuc2UiOiAiTUlUIiwKICAidHlwZSI6ICJjb21tb25qcyIsCiAgInJlcG9zaXRvcnkiOiB7CiAgICAidHlwZSI6ICJnaXQiLAogICAgInVybCI6ICJnaXQraHR0cHM6Ly9naXRodWIuY29tL2FqYXlkdWRoYW1sMDEtYXJjaC9oaW5hdGEtYm90LmdpdCIKICB9LAogICJidWdzIjogewogICAgInVybCI6ICJodHRwczovL2dpdGh1Yi5jb20vYWpheWR1ZGhhbWwwMS1hcmNoL2hpbmF0YS1ib3QvaXNzdWVzIgogIH0sCiAgImhvbWVwYWdlIjogImh0dHBzOi8vZ2l0aHViLmNvbS9hamF5ZHVkaGFtbDAxLWFyY2gvaGluYXRhLWJvdCNyZWFkbWUiLAogICJlbmdpbmVzIjogewogICAgIm5vZGUiOiAiPj0xOC4xOC4wIgogIH0sCiAgImRlcGVuZGVuY2llcyI6IHsKICAgICJheGlvcyI6ICJeMS4xNi4xIiwKICAgICJkaXNjb3JkLmpzIjogIl4xNC4yNi40IiwKICAgICJkb3RlbnYiOiAiXjE3LjQuMiIKICB9Cn0K"
Write-B64 ".gitignore" "IyBEZXBlbmRlbmNpZXMKbm9kZV9tb2R1bGVzLwoKIyBTZWNyZXRzIGFuZCBsb2NhbCBjb25maWd1cmF0aW9uCi5lbnYKLmVudi4qCiEuZW52LmV4YW1wbGUKY29uZmlnLmpzb24KCiMgUnVudGltZSBkYXRhCmRhdGEvKi5qc29uCiFkYXRhLy5naXRrZWVwCgojIEVkaXRvcnMKLnZzY29kZS8KLmlkZWEvCgojIE9TIGZpbGVzCi5EU19TdG9yZQpUaHVtYnMuZGIKCiMgTG9ncwoqLmxvZwpucG0tZGVidWcubG9nKgp5YXJuLWRlYnVnLmxvZyoKeWFybi1lcnJvci5sb2cqCgojIExvY2FsIHVwZ3JhZGUgYmFja3Vwcwoub3NzLWJhY2t1cC8K"
Write-B64 "config.example.json" "ewogICJjb2xvcnMiOiB7CiAgICAicHJpbWFyeSI6ICIjNTg2NUYyIiwKICAgICJzdWNjZXNzIjogIiM1N0YyODciLAogICAgIndhcm5pbmciOiAiI0ZFRTc1QyIsCiAgICAiZGFuZ2VyIjogIiNFRDQyNDUiLAogICAgImluZm8iOiAiIzM0OThEQiIsCiAgICAibmV1dHJhbCI6ICIjMkIyRDMxIgogIH0sCiAgImRlZmF1bHRTZXR0aW5ncyI6IHsKICAgICJ3ZWxjb21lQ2hhbm5lbElkIjogIiIsCiAgICAiZmFyZXdlbGxDaGFubmVsSWQiOiAiIiwKICAgICJ3ZWxjb21lUm9sZU5hbWUiOiAiTWVtYmVyIiwKICAgICJ0aWNrZXRDYXRlZ29yeUlkIjogIiIsCiAgICAidGlja2V0U3RhZmZSb2xlSWQiOiAiIiwKICAgICJsb2dDaGFubmVsSWQiOiAiIiwKICAgICJqb2luVG9DcmVhdGVDaGFubmVsSWQiOiAiIiwKICAgICJibG9ja2VkV29yZHMiOiBbCiAgICAgICJleGFtcGxlLWJsb2NrZWQtd29yZCIKICAgIF0sCiAgICAibGV2ZWxSb2xlcyI6IHt9LAogICAgIm1lbWJlckNvdW50Q2hhbm5lbElkIjogIiIKICB9Cn0K"
Write-B64 "CONTRIBUTING.md" "IyBDb250cmlidXRpbmcgdG8gSGluYXRhCgpUaGFua3MgZm9yIGhlbHBpbmcgaW1wcm92ZSBIaW5hdGEuCgojIyBCZWZvcmUgeW91IHN0YXJ0CgotIFNlYXJjaCBleGlzdGluZyBpc3N1ZXMgYmVmb3JlIG9wZW5pbmcgYSBkdXBsaWNhdGUuCi0gTmV2ZXIgaW5jbHVkZSBEaXNjb3JkIHRva2VucywgYC5lbnZgIGNvbnRlbnRzLCBwcml2YXRlIGNyZWRlbnRpYWxzLCBvciBzZW5zaXRpdmUgc2VydmVyIGRhdGEuCi0gS2VlcCBwdWxsIHJlcXVlc3RzIGZvY3VzZWQgb24gb25lIGNoYW5nZSB3aGVuIHByYWN0aWNhbC4KCiMjIExvY2FsIHNldHVwCgpgYGBiYXNoCmdpdCBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vYWpheWR1ZGhhbWwwMS1hcmNoL2hpbmF0YS1ib3QuZ2l0CmNkIGhpbmF0YS1ib3QKbnBtIGluc3RhbGwKY3AgLmVudi5leGFtcGxlIC5lbnYKY3AgY29uZmlnLmV4YW1wbGUuanNvbiBjb25maWcuanNvbgpgYGAKCk9uIFdpbmRvd3MgUG93ZXJTaGVsbCwgdXNlIGBDb3B5LUl0ZW1gIGluc3RlYWQgb2YgYGNwYCBpZiBwcmVmZXJyZWQuCgojIyBEZXZlbG9wbWVudCB3b3JrZmxvdwoKMS4gQ3JlYXRlIGEgYnJhbmNoOgogICBgYGBiYXNoCiAgIGdpdCBjaGVja291dCAtYiBmZWF0L3Nob3J0LWRlc2NyaXB0aW9uCiAgIGBgYAoyLiBNYWtlIHlvdXIgY2hhbmdlcy4KMy4gUnVuOgogICBgYGBiYXNoCiAgIG5wbSBydW4gY2hlY2sKICAgbnBtIHRlc3QKICAgYGBgCjQuIENvbW1pdCB3aXRoIGEgY2xlYXIgbWVzc2FnZS4KNS4gUHVzaCB5b3VyIGJyYW5jaCBhbmQgb3BlbiBhIHB1bGwgcmVxdWVzdC4KCiMjIENvbW1pdCBzdHlsZQoKQ29udmVudGlvbmFsLXN0eWxlIHByZWZpeGVzIGFyZSBlbmNvdXJhZ2VkOgoKLSBgZmVhdDpgIG5ldyBmdW5jdGlvbmFsaXR5Ci0gYGZpeDpgIGJ1ZyBmaXgKLSBgZG9jczpgIGRvY3VtZW50YXRpb24KLSBgdGVzdDpgIHRlc3RzCi0gYHJlZmFjdG9yOmAgaW50ZXJuYWwgY29kZSBpbXByb3ZlbWVudAotIGBjaG9yZTpgIG1haW50ZW5hbmNlCgpFeGFtcGxlczoKCmBgYHRleHQKZmVhdDogYWRkIGNvbmZpZ3VyYWJsZSBhbnRpLXNwYW0gdGhyZXNob2xkCmZpeDogcHJldmVudCBkdXBsaWNhdGUgZHluYW1pYyB2b2ljZSBjaGFubmVscwpkb2NzOiBjbGFyaWZ5IERpc2NvcmQgaW50ZW50IHJlcXVpcmVtZW50cwpgYGAKCiMjIFB1bGwgcmVxdWVzdHMKCkEgZ29vZCBwdWxsIHJlcXVlc3Qgc2hvdWxkIGV4cGxhaW46CgotIHdoYXQgY2hhbmdlZAotIHdoeSBpdCBjaGFuZ2VkCi0gaG93IGl0IHdhcyB0ZXN0ZWQKLSBhbnkgYmVoYXZpb3Igb3IgY29uZmlndXJhdGlvbiBjaGFuZ2VzCgpTY3JlZW5zaG90cyBhcmUgd2VsY29tZSBmb3IgaW50ZXJhY3Rpb24vVUkgY2hhbmdlcy4KCiMjIENvZGUgZXhwZWN0YXRpb25zCgotIEtlZXAgc2VjcmV0cyBvdXQgb2Ygc291cmNlIGNvbnRyb2wuCi0gUHJlZmVyIGNsZWFyIG5hbWVzIG92ZXIgY2xldmVyIGFic3RyYWN0aW9ucy4KLSBIYW5kbGUgRGlzY29yZCBwZXJtaXNzaW9uIGZhaWx1cmVzIGdyYWNlZnVsbHkuCi0gQXZvaWQgYnJlYWtpbmcgZXhpc3RpbmcgY29uZmlndXJhdGlvbiB3aXRob3V0IGRvY3VtZW50aW5nIG1pZ3JhdGlvbiBzdGVwcy4KLSBBZGQgb3IgdXBkYXRlIHRlc3RzIHdoZW4gcHJhY3RpY2FsLgoKIyMgUmVwb3J0aW5nIHNlY3VyaXR5IGlzc3VlcwoKUGxlYXNlIGZvbGxvdyBbU0VDVVJJVFkubWRdKFNFQ1VSSVRZLm1kKS4K"
Write-B64 "SECURITY.md" "IyBTZWN1cml0eSBQb2xpY3kKCiMjIFN1cHBvcnRlZCB2ZXJzaW9ucwoKU2VjdXJpdHkgZml4ZXMgYXJlIHRhcmdldGVkIGF0IHRoZSBsYXRlc3QgY29kZSBvbiBgbWFpbmAgYW5kIHRoZSBsYXRlc3QgcHVibGlzaGVkIHJlbGVhc2UuCgojIyBSZXBvcnRpbmcgYSB2dWxuZXJhYmlsaXR5CgpQbGVhc2UgKipkbyBub3Qgb3BlbiBhIHB1YmxpYyBpc3N1ZSBjb250YWluaW5nIGV4cGxvaXQgZGV0YWlscywgdG9rZW5zLCBjcmVkZW50aWFscywgcHJpdmF0ZSBzZXJ2ZXIgaW5mb3JtYXRpb24sIG9yIG90aGVyIHNlbnNpdGl2ZSBkYXRhKiouCgpQcmVmZXJyZWQgcmVwb3J0aW5nIHBhdGg6CgoxLiBVc2UgR2l0SHViJ3MgcHJpdmF0ZSB2dWxuZXJhYmlsaXR5IHJlcG9ydGluZyAvIFNlY3VyaXR5IEFkdmlzb3J5IGZsb3cgZm9yIHRoaXMgcmVwb3NpdG9yeSB3aGVuIGF2YWlsYWJsZS4KMi4gSWYgcHJpdmF0ZSByZXBvcnRpbmcgaXMgdW5hdmFpbGFibGUsIG9wZW4gYSBtaW5pbWFsIHB1YmxpYyBpc3N1ZSBzdGF0aW5nIHRoYXQgeW91IGZvdW5kIGEgc2VjdXJpdHkgcHJvYmxlbSAqKndpdGhvdXQgaW5jbHVkaW5nIHNlbnNpdGl2ZSB0ZWNobmljYWwgZGV0YWlscyoqLCBzbyB0aGUgbWFpbnRhaW5lciBjYW4gYXJyYW5nZSBhIHNhZmVyIGNoYW5uZWwuCgpJbmNsdWRlLCB3aGVuIHNhZmU6CgotIGFmZmVjdGVkIGZlYXR1cmUvZmlsZQotIGltcGFjdAotIHJlcHJvZHVjdGlvbiBjb25kaXRpb25zCi0gc3VnZ2VzdGVkIG1pdGlnYXRpb24sIGlmIGtub3duCgojIyBEaXNjb3JkIGJvdCBzZWNyZXRzCgpBIERpc2NvcmQgYm90IHRva2VuIGdpdmVzIGNvbnRyb2wgb2YgdGhlIGJvdCBhY2NvdW50LiBJZiBhIHRva2VuIGlzIGV2ZXIgZXhwb3NlZDoKCjEuIFJlc2V0IGl0IGltbWVkaWF0ZWx5IGluIHRoZSBEaXNjb3JkIERldmVsb3BlciBQb3J0YWwuCjIuIFVwZGF0ZSB0aGUgc2VjcmV0IGluIHlvdXIgZGVwbG95bWVudCBlbnZpcm9ubWVudC4KMy4gUmVtb3ZlIGl0IGZyb20gc291cmNlIGNvbnRyb2wgYW5kIGNvbnNpZGVyIGNsZWFuaW5nIEdpdCBoaXN0b3J5Lgo0LiBSZXZpZXcgcmVjZW50IGJvdCBhY3Rpdml0eS4KCk5ldmVyIGNvbW1pdCBgLmVudmAgZmlsZXMgb3IgcHJvZHVjdGlvbiBjcmVkZW50aWFscy4K"
Write-B64 "CODE_OF_CONDUCT.md" "IyBDb2RlIG9mIENvbmR1Y3QKCkhpbmF0YSBhaW1zIHRvIGJlIGEgd2VsY29taW5nIG9wZW4tc291cmNlIHByb2plY3QuCgojIyBFeHBlY3RlZCBiZWhhdmlvcgoKQ29udHJpYnV0b3JzIGFuZCBwYXJ0aWNpcGFudHMgc2hvdWxkOgoKLSBiZSByZXNwZWN0ZnVsIGFuZCBjb25zdHJ1Y3RpdmUKLSBkaXNjdXNzIHRlY2huaWNhbCBkaXNhZ3JlZW1lbnRzIHdpdGhvdXQgcGVyc29uYWwgYXR0YWNrcwotIGdpdmUgdXNlZnVsIGZlZWRiYWNrIGFuZCBhY2NlcHQgcmVhc29uYWJsZSBmZWVkYmFjayBpbiByZXR1cm4KLSByZXNwZWN0IHByaXZhY3kgYW5kIGF2b2lkIHB1Ymxpc2hpbmcgYW5vdGhlciBwZXJzb24ncyBzZW5zaXRpdmUgaW5mb3JtYXRpb24KLSBrZWVwIGlzc3VlcyBhbmQgcHVsbCByZXF1ZXN0cyByZWxldmFudCB0byB0aGUgcHJvamVjdAoKIyMgVW5hY2NlcHRhYmxlIGJlaGF2aW9yCgpIYXJhc3NtZW50LCB0aHJlYXRzLCBkaXNjcmltaW5hdGlvbiwgZGVsaWJlcmF0ZSBkaXNydXB0aW9uLCBkb3h4aW5nLCBzcGFtLCBhbmQgYWJ1c2l2ZSBjb25kdWN0IGFyZSBub3Qgd2VsY29tZS4KCiMjIEVuZm9yY2VtZW50CgpQcm9qZWN0IG1haW50YWluZXJzIG1heSBlZGl0LCBoaWRlLCBsb2NrLCBvciByZW1vdmUgY29udHJpYnV0aW9ucyB0aGF0IHZpb2xhdGUgdGhlc2UgZXhwZWN0YXRpb25zIGFuZCBtYXkgcmVzdHJpY3QgcGFydGljaXBhdGlvbiB3aGVuIG5lY2Vzc2FyeSB0byBwcm90ZWN0IHRoZSBwcm9qZWN0IGFuZCBpdHMgY29tbXVuaXR5LgoKSWYgYSBzaXR1YXRpb24gaW52b2x2ZXMgYSBzZWN1cml0eSB2dWxuZXJhYmlsaXR5LCB1c2UgdGhlIHByb2Nlc3MgaW4gW1NFQ1VSSVRZLm1kXShTRUNVUklUWS5tZCkgaW5zdGVhZCBvZiBwb3N0aW5nIHNlbnNpdGl2ZSBkZXRhaWxzIHB1YmxpY2x5Lgo="
Write-B64 "SUPPORT.md" "IyBTdXBwb3J0CgpGb3IgaGVscCB1c2luZyBIaW5hdGE6CgoxLiBSZWFkIHRoZSBbUkVBRE1FXShSRUFETUUubWQpLCBlc3BlY2lhbGx5IFF1aWNrIHN0YXJ0IGFuZCBDb25maWd1cmF0aW9uLgoyLiBTZWFyY2ggZXhpc3RpbmcgR2l0SHViIGlzc3Vlcy4KMy4gSWYgeW91IGZvdW5kIGEgcmVwcm9kdWNpYmxlIGJ1Zywgb3BlbiBhIGJ1ZyByZXBvcnQuCjQuIElmIHlvdSB3YW50IGEgbmV3IGNhcGFiaWxpdHksIG9wZW4gYSBmZWF0dXJlIHJlcXVlc3QuCgpXaGVuIGFza2luZyBmb3IgaGVscCwgaW5jbHVkZToKCi0gTm9kZS5qcyB2ZXJzaW9uIChgbm9kZSAtLXZlcnNpb25gKQotIG5wbSB2ZXJzaW9uIChgbnBtIC0tdmVyc2lvbmApCi0gb3BlcmF0aW5nIHN5c3RlbSAvIGhvc3RpbmcgcGxhdGZvcm0KLSByZWxldmFudCBlcnJvciBtZXNzYWdlCi0gc3RlcHMgdG8gcmVwcm9kdWNlCgpEbyAqKm5vdCoqIGluY2x1ZGUgeW91ciBEaXNjb3JkIHRva2VuLCBgLmVudmAsIHByaXZhdGUgY3JlZGVudGlhbHMsIG9yIHNlbnNpdGl2ZSBzZXJ2ZXIgZGF0YS4K"
Write-B64 "ROADMAP.md" "IyBIaW5hdGEgUm9hZG1hcAoKVGhpcyByb2FkbWFwIGlzIGRpcmVjdGlvbmFsIHJhdGhlciB0aGFuIGEgcHJvbWlzZSBvZiBkYXRlcy4KCiMjIE5lYXIgdGVybQoKLSBleHBhbmQgYXV0b21hdGVkIHRlc3RzIGZvciBjb21tYW5kcywgaGFuZGxlcnMsIGFuZCBwZXJtaXNzaW9uIGNoZWNrcwotIGltcHJvdmUgZXJyb3IgaGFuZGxpbmcgYW5kIHVzZXItZmFjaW5nIGZhaWx1cmUgbWVzc2FnZXMKLSBtYWtlIG1vcmUgbW9kZXJhdGlvbiB0aHJlc2hvbGRzIGNvbmZpZ3VyYWJsZQotIGltcHJvdmUgZG9jdW1lbnRhdGlvbiBhbmQgc2VsZi1ob3N0aW5nIGV4YW1wbGVzCi0gYWRkIGJldHRlciB2YWxpZGF0aW9uIGZvciBgY29uZmlnLmpzb25gCgojIyBNZWRpdW0gdGVybQoKLSBwZXItZ3VpbGQgY29uZmlndXJhdGlvbiBpbnN0ZWFkIG9mIGEgc2luZ2xlIHNlcnZlci1vcmllbnRlZCBjb25maWcKLSBwbHVnZ2FibGUgcGVyc2lzdGVuY2UgbGF5ZXIKLSBTUUxpdGUgYWRhcHRlciBmb3IgZWFzeSBzZWxmLWhvc3RpbmcKLSBkYXRhYmFzZSBvcHRpb24gZm9yIGxhcmdlciBkZXBsb3ltZW50cwotIG1pZ3JhdGlvbiB1dGlsaXRpZXMgZm9yIGxvY2FsIEpTT04gZGF0YQotIGltcHJvdmVkIGxvZ2dpbmcgYW5kIG9ic2VydmFiaWxpdHkKCiMjIExvbmdlciB0ZXJtCgotIG9wdGlvbmFsIHdlYiBkYXNoYm9hcmQKLSBwbHVnaW4vbW9kdWxlIEFQSSBmb3IgY29tbXVuaXR5IGV4dGVuc2lvbnMKLSBsb2NhbGl6YXRpb24gc3VwcG9ydAotIHJpY2hlciBtb2RlcmF0aW9uIHJ1bGUgZW5naW5lCi0gZG9jdW1lbnRlZCBkZXBsb3ltZW50IHJlY2lwZXMgZm9yIGNvbW1vbiBob3N0cwoKSWRlYXMgYW5kIGNvbnRyaWJ1dGlvbnMgYXJlIHdlbGNvbWUgdGhyb3VnaCBHaXRIdWIgaXNzdWVzIGFuZCBwdWxsIHJlcXVlc3RzLgo="
Write-B64 "CHANGELOG.md" "IyBDaGFuZ2Vsb2cKCkFsbCBub3RhYmxlIHByb2plY3QgY2hhbmdlcyB3aWxsIGJlIGRvY3VtZW50ZWQgaGVyZS4KCiMjIFVucmVsZWFzZWQKCiMjIyBBZGRlZAoKLSBvcGVuLXNvdXJjZSBwcm9qZWN0IGRvY3VtZW50YXRpb24KLSBNSVQgbGljZW5zZQotIGNvbnRyaWJ1dGlvbiBhbmQgc2VjdXJpdHkgZ3VpZGFuY2UKLSBHaXRIdWIgaXNzdWUgYW5kIHB1bGwgcmVxdWVzdCB0ZW1wbGF0ZXMKLSBDSSB3b3JrZmxvdyBhbmQgZGVwZW5kZW5jeSB1cGRhdGUgY29uZmlndXJhdGlvbgotIHJldXNhYmxlIGBjb25maWcuZXhhbXBsZS5qc29uYAotIGJhc2ljIHByb2plY3QgbWV0YWRhdGEgdGVzdHMKCiMjIyBDaGFuZ2VkCgotIHByb2plY3QgYnJhbmRpbmcgYW5kIFJFQURNRSB1cGRhdGVkIGZvciByZXVzYWJsZSBzZWxmLWhvc3RpbmcKLSBwYWNrYWdlIG1ldGFkYXRhIGltcHJvdmVkCi0gc2VydmVyLXNwZWNpZmljIGNvbmZpZ3VyYXRpb24gYW5kIHJ1bnRpbWUgZGF0YSBleGNsdWRlZCBmcm9tIGZ1dHVyZSBjb21taXRzCg=="
Write-B64 "docs/ARCHITECTURE.md" "IyBBcmNoaXRlY3R1cmUKCkhpbmF0YSB1c2VzIGEgbW9kdWxhciBDb21tb25KUyBzdHJ1Y3R1cmUgYnVpbHQgb24gRGlzY29yZC5qcy4KCiMjIEVudHJ5IHBvaW50CgpgaW5kZXguanNgOgoKLSBsb2FkcyBlbnZpcm9ubWVudCB2YXJpYWJsZXMgd2l0aCBgZG90ZW52YAotIGNyZWF0ZXMgdGhlIERpc2NvcmQgY2xpZW50IHdpdGggcmVxdWlyZWQgZ2F0ZXdheSBpbnRlbnRzCi0gYXR0YWNoZXMgdGhlIGNvbW1hbmQgY29sbGVjdGlvbiBhbmQgY29uZmlndXJhdGlvbgotIGxvYWRzIGhhbmRsZXIgbW9kdWxlcyBmcm9tIGBzcmMvaGFuZGxlcnNgCi0gc3RhcnRzIHRoZSBsaWdodHdlaWdodCBIVFRQIGhlYWx0aCBlbmRwb2ludAotIGxvZ3MgaW4gdXNpbmcgYERJU0NPUkRfVE9LRU5gCgojIyBIYW5kbGVycwoKYHNyYy9oYW5kbGVycy9gIGlzIHJlc3BvbnNpYmxlIGZvciBkaXNjb3ZlcmluZyBhbmQgcmVnaXN0ZXJpbmcgYXBwbGljYXRpb24gYmVoYXZpb3Igc3VjaCBhcyBjb21tYW5kcyBhbmQgZXZlbnRzLgoKVGhpcyBrZWVwcyBzdGFydHVwIGxvZ2ljIGluIGBpbmRleC5qc2AgcmVsYXRpdmVseSBzbWFsbCBhbmQgYWxsb3dzIGZlYXR1cmVzIHRvIHJlbWFpbiBtb2R1bGFyLgoKIyMgQ29tbWFuZHMKCmBzcmMvY29tbWFuZHMvYCBpcyBncm91cGVkIGJ5IGZlYXR1cmUgY2F0ZWdvcnk6CgotIGBmdW4vYAotIGBtb2RlcmF0aW9uL2AKLSBgdGlja2V0cy9gCi0gYHV0aWxpdHkvYAoKTmV3IGNvbW1hbmRzIHNob3VsZCBmb2xsb3cgdGhlIHNhbWUgZXhwb3J0IGNvbnRyYWN0IHVzZWQgYnkgZXhpc3RpbmcgY29tbWFuZHMgYW5kIHNob3VsZCBiZSBwbGFjZWQgaW4gdGhlIG1vc3QgYXBwcm9wcmlhdGUgY2F0ZWdvcnkuCgojIyBFdmVudHMKCmBzcmMvZXZlbnRzL2AgY29udGFpbnMgRGlzY29yZCBldmVudCBsaXN0ZW5lcnMgYW5kIGJhY2tncm91bmQgYXV0b21hdGlvbi4KCkV4YW1wbGVzIG9mIGJlaGF2aW9yIGltcGxlbWVudGVkIHRocm91Z2ggZXZlbnRzIGNhbiBpbmNsdWRlOgoKLSBpbnRlcmFjdGlvbiBoYW5kbGluZwotIG1lc3NhZ2UtYmFzZWQgYXV0b21hdGlvbgotIG1lbWJlciBqb2luL2xlYXZlIGJlaGF2aW9yCi0gdm9pY2Ugc3RhdGUgY2hhbmdlcwotIGxldmVsaW5nIGFuZCBtb2RlcmF0aW9uIGF1dG9tYXRpb24KCiMjIENvbmZpZ3VyYXRpb24KClNlY3JldHMgYmVsb25nIGluIGAuZW52YC4KClJldXNhYmxlIHNlcnZlciBzZXR0aW5ncyBhcmUgZG9jdW1lbnRlZCBpbiBgY29uZmlnLmV4YW1wbGUuanNvbmAuIEVhY2ggZGVwbG95bWVudCBzaG91bGQgY3JlYXRlIGl0cyBvd24gaWdub3JlZCBgY29uZmlnLmpzb25gLgoKIyMgUGVyc2lzdGVuY2UKClRoZSBjdXJyZW50IHByb2plY3QgdXNlcyBsb2NhbCBKU09OIGZpbGVzIGZvciBzb21lIHJ1bnRpbWUgc3RhdGUuIFRoaXMgaXMgc2ltcGxlIGZvciBhIHNpbmdsZSBpbnN0YW5jZSwgYnV0IGxhcmdlciBkZXBsb3ltZW50cyBzaG91bGQgZXZlbnR1YWxseSB1c2UgYSBkYXRhYmFzZSBvciBhbm90aGVyIHNoYXJlZCBwZXJzaXN0ZW5jZSBsYXllci4KClJ1bnRpbWUgSlNPTiBmaWxlcyBhcmUgZXhjbHVkZWQgZnJvbSBHaXQuCg=="
Write-B64 "tests/project.test.js" "Y29uc3QgdGVzdCA9IHJlcXVpcmUoJ25vZGU6dGVzdCcpOwpjb25zdCBhc3NlcnQgPSByZXF1aXJlKCdub2RlOmFzc2VydC9zdHJpY3QnKTsKY29uc3QgZnMgPSByZXF1aXJlKCdub2RlOmZzJyk7CmNvbnN0IHBhdGggPSByZXF1aXJlKCdub2RlOnBhdGgnKTsKCmNvbnN0IHJvb3QgPSBwYXRoLnJlc29sdmUoX19kaXJuYW1lLCAnLi4nKTsKCnRlc3QoJ3BhY2thZ2UgbWV0YWRhdGEgaXMgc3VpdGFibGUgZm9yIGFuIG9wZW4tc291cmNlIHByb2plY3QnLCAoKSA9PiB7CiAgY29uc3QgcGtnID0gSlNPTi5wYXJzZShmcy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKHJvb3QsICdwYWNrYWdlLmpzb24nKSwgJ3V0ZjgnKSk7CgogIGFzc2VydC5lcXVhbChwa2cubmFtZSwgJ2hpbmF0YS1kaXNjb3JkLWJvdCcpOwogIGFzc2VydC5lcXVhbChwa2cubGljZW5zZSwgJ01JVCcpOwogIGFzc2VydC5lcXVhbChwa2cubWFpbiwgJ2luZGV4LmpzJyk7CiAgYXNzZXJ0LmVxdWFsKHBrZy5zY3JpcHRzLnN0YXJ0LCAnbm9kZSBpbmRleC5qcycpOwogIGFzc2VydC5vayhwa2cucmVwb3NpdG9yeSk7CiAgYXNzZXJ0Lm9rKEFycmF5LmlzQXJyYXkocGtnLmtleXdvcmRzKSk7CiAgYXNzZXJ0Lm9rKHBrZy5rZXl3b3Jkcy5pbmNsdWRlcygnZGlzY29yZC1ib3QnKSk7Cn0pOwoKdGVzdCgnZXhhbXBsZSBjb25maWd1cmF0aW9uIGhhcyB0aGUgZXhwZWN0ZWQgc2hhcGUnLCAoKSA9PiB7CiAgY29uc3QgY29uZmlnID0gSlNPTi5wYXJzZSgKICAgIGZzLnJlYWRGaWxlU3luYyhwYXRoLmpvaW4ocm9vdCwgJ2NvbmZpZy5leGFtcGxlLmpzb24nKSwgJ3V0ZjgnKQogICk7CgogIGFzc2VydC5vayhjb25maWcuY29sb3JzKTsKICBhc3NlcnQub2soY29uZmlnLmRlZmF1bHRTZXR0aW5ncyk7CiAgYXNzZXJ0LmVxdWFsKHR5cGVvZiBjb25maWcuZGVmYXVsdFNldHRpbmdzLndlbGNvbWVSb2xlTmFtZSwgJ3N0cmluZycpOwogIGFzc2VydC5vayhBcnJheS5pc0FycmF5KGNvbmZpZy5kZWZhdWx0U2V0dGluZ3MuYmxvY2tlZFdvcmRzKSk7CiAgYXNzZXJ0LmVxdWFsKHR5cGVvZiBjb25maWcuZGVmYXVsdFNldHRpbmdzLmxldmVsUm9sZXMsICdvYmplY3QnKTsKfSk7Cgp0ZXN0KCdzZWNyZXQgZW52aXJvbm1lbnQgZmlsZSBpcyBpZ25vcmVkIHdoaWxlIGV4YW1wbGUgaXMgdHJhY2tlZCcsICgpID0+IHsKICBjb25zdCBpZ25vcmUgPSBmcy5yZWFkRmlsZVN5bmMocGF0aC5qb2luKHJvb3QsICcuZ2l0aWdub3JlJyksICd1dGY4Jyk7CgogIGFzc2VydC5tYXRjaChpZ25vcmUsIC9eXC5lbnYkL20pOwogIGFzc2VydC5tYXRjaChpZ25vcmUsIC9eIVwuZW52XC5leGFtcGxlJC9tKTsKfSk7Cg=="
Write-B64 ".github/workflows/ci.yml" "bmFtZTogQ0kKCm9uOgogIHB1c2g6CiAgICBicmFuY2hlczogWyJtYWluIl0KICBwdWxsX3JlcXVlc3Q6CgpwZXJtaXNzaW9uczoKICBjb250ZW50czogcmVhZAoKam9iczoKICB0ZXN0OgogICAgcnVucy1vbjogdWJ1bnR1LWxhdGVzdAoKICAgIHN0cmF0ZWd5OgogICAgICBtYXRyaXg6CiAgICAgICAgbm9kZS12ZXJzaW9uOiBbMjAueCwgMjIueF0KCiAgICBzdGVwczoKICAgICAgLSBuYW1lOiBDaGVja291dAogICAgICAgIHVzZXM6IGFjdGlvbnMvY2hlY2tvdXRAdjQKCiAgICAgIC0gbmFtZTogVXNlIE5vZGUuanMKICAgICAgICB1c2VzOiBhY3Rpb25zL3NldHVwLW5vZGVAdjQKICAgICAgICB3aXRoOgogICAgICAgICAgbm9kZS12ZXJzaW9uOiAke3sgbWF0cml4Lm5vZGUtdmVyc2lvbiB9fQogICAgICAgICAgY2FjaGU6IG5wbQoKICAgICAgLSBuYW1lOiBJbnN0YWxsIGRlcGVuZGVuY2llcwogICAgICAgIHJ1bjogbnBtIGNpCgogICAgICAtIG5hbWU6IFN5bnRheCBjaGVjawogICAgICAgIHJ1bjogbnBtIHJ1biBjaGVjawoKICAgICAgLSBuYW1lOiBUZXN0cwogICAgICAgIHJ1bjogbnBtIHRlc3QK"
Write-B64 ".github/dependabot.yml" "dmVyc2lvbjogMgp1cGRhdGVzOgogIC0gcGFja2FnZS1lY29zeXN0ZW06ICJucG0iCiAgICBkaXJlY3Rvcnk6ICIvIgogICAgc2NoZWR1bGU6CiAgICAgIGludGVydmFsOiAid2Vla2x5IgogICAgb3Blbi1wdWxsLXJlcXVlc3RzLWxpbWl0OiA1Cg=="
Write-B64 ".github/CODEOWNERS" "KiBAYWpheWR1ZGhhbWwwMS1hcmNoCg=="
Write-B64 ".github/pull_request_template.md" "IyMgV2hhdCBjaGFuZ2VkPwoKPCEtLSBEZXNjcmliZSB0aGUgY2hhbmdlIGNsZWFybHkuIC0tPgoKIyMgV2h5PwoKPCEtLSBFeHBsYWluIHRoZSBwcm9ibGVtIG9yIGdvYWwuIC0tPgoKIyMgSG93IHdhcyBpdCB0ZXN0ZWQ/CgotIFsgXSBgbnBtIHJ1biBjaGVja2AKLSBbIF0gYG5wbSB0ZXN0YAotIFsgXSBUZXN0ZWQgcmVsZXZhbnQgRGlzY29yZCBiZWhhdmlvciBtYW51YWxseSwgaWYgYXBwbGljYWJsZQoKIyMgQ2hlY2tsaXN0CgotIFsgXSBJIGRpZCBub3QgaW5jbHVkZSB0b2tlbnMsIGAuZW52YCBjb250ZW50cywgb3Igc2Vuc2l0aXZlIHNlcnZlciBkYXRhLgotIFsgXSBJIHVwZGF0ZWQgZG9jdW1lbnRhdGlvbiB3aGVuIGJlaGF2aW9yL2NvbmZpZ3VyYXRpb24gY2hhbmdlZC4KLSBbIF0gSSBrZXB0IHRoaXMgcHVsbCByZXF1ZXN0IGZvY3VzZWQuCg=="
Write-B64 ".github/ISSUE_TEMPLATE/bug_report.yml" "bmFtZTogQnVnIHJlcG9ydApkZXNjcmlwdGlvbjogUmVwb3J0IGEgcmVwcm9kdWNpYmxlIHByb2JsZW0gaW4gSGluYXRhCnRpdGxlOiAiW0J1Z106ICIKbGFiZWxzOiBbImJ1ZyJdCmJvZHk6CiAgLSB0eXBlOiBtYXJrZG93bgogICAgYXR0cmlidXRlczoKICAgICAgdmFsdWU6IHwKICAgICAgICBUaGFua3MgZm9yIHJlcG9ydGluZyBhIGJ1Zy4gKipOZXZlciBpbmNsdWRlIHlvdXIgRGlzY29yZCB0b2tlbiwgYC5lbnZgLCBjcmVkZW50aWFscywgb3IgcHJpdmF0ZSBzZXJ2ZXIgZGF0YS4qKgoKICAtIHR5cGU6IHRleHRhcmVhCiAgICBpZDogc3VtbWFyeQogICAgYXR0cmlidXRlczoKICAgICAgbGFiZWw6IFdoYXQgaGFwcGVuZWQ/CiAgICAgIGRlc2NyaXB0aW9uOiBEZXNjcmliZSB0aGUgcHJvYmxlbSBhbmQgd2hhdCB5b3UgZXhwZWN0ZWQgaW5zdGVhZC4KICAgIHZhbGlkYXRpb25zOgogICAgICByZXF1aXJlZDogdHJ1ZQoKICAtIHR5cGU6IHRleHRhcmVhCiAgICBpZDogcmVwcm9kdWNlCiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogU3RlcHMgdG8gcmVwcm9kdWNlCiAgICAgIHBsYWNlaG9sZGVyOiB8CiAgICAgICAgMS4gUnVuIC4uLgogICAgICAgIDIuIFVzZSBjb21tYW5kIC4uLgogICAgICAgIDMuIFNlZSBlcnJvciAuLi4KICAgIHZhbGlkYXRpb25zOgogICAgICByZXF1aXJlZDogdHJ1ZQoKICAtIHR5cGU6IGlucHV0CiAgICBpZDogbm9kZQogICAgYXR0cmlidXRlczoKICAgICAgbGFiZWw6IE5vZGUuanMgdmVyc2lvbgogICAgICBwbGFjZWhvbGRlcjogImUuZy4gdjIyLngiCiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWlyZWQ6IHRydWUKCiAgLSB0eXBlOiBpbnB1dAogICAgaWQ6IGVudmlyb25tZW50CiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogRW52aXJvbm1lbnQKICAgICAgcGxhY2Vob2xkZXI6ICJXaW5kb3dzIDExLCBVYnVudHUsIFJlbmRlciwgS295ZWIsIGV0Yy4iCiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWlyZWQ6IHRydWUKCiAgLSB0eXBlOiB0ZXh0YXJlYQogICAgaWQ6IGxvZ3MKICAgIGF0dHJpYnV0ZXM6CiAgICAgIGxhYmVsOiBSZWxldmFudCBzYW5pdGl6ZWQgbG9ncwogICAgICBkZXNjcmlwdGlvbjogUmVtb3ZlIHRva2VucywgSURzIHlvdSBjb25zaWRlciBwcml2YXRlLCBhbmQgb3RoZXIgc2Vuc2l0aXZlIHZhbHVlcyBiZWZvcmUgcG9zdGluZy4KICAgICAgcmVuZGVyOiBzaGVsbAo="
Write-B64 ".github/ISSUE_TEMPLATE/feature_request.yml" "bmFtZTogRmVhdHVyZSByZXF1ZXN0CmRlc2NyaXB0aW9uOiBTdWdnZXN0IGFuIGltcHJvdmVtZW50IGZvciBIaW5hdGEKdGl0bGU6ICJbRmVhdHVyZV06ICIKbGFiZWxzOiBbImVuaGFuY2VtZW50Il0KYm9keToKICAtIHR5cGU6IHRleHRhcmVhCiAgICBpZDogcHJvYmxlbQogICAgYXR0cmlidXRlczoKICAgICAgbGFiZWw6IFByb2JsZW0gb3IgdXNlIGNhc2UKICAgICAgZGVzY3JpcHRpb246IFdoYXQgcHJvYmxlbSB3b3VsZCB0aGlzIGZlYXR1cmUgc29sdmU/CiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWlyZWQ6IHRydWUKCiAgLSB0eXBlOiB0ZXh0YXJlYQogICAgaWQ6IHByb3Bvc2FsCiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogUHJvcG9zZWQgc29sdXRpb24KICAgICAgZGVzY3JpcHRpb246IERlc2NyaWJlIGhvdyB5b3UgdGhpbmsgaXQgc2hvdWxkIHdvcmsuCiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWlyZWQ6IHRydWUKCiAgLSB0eXBlOiB0ZXh0YXJlYQogICAgaWQ6IGFsdGVybmF0aXZlcwogICAgYXR0cmlidXRlczoKICAgICAgbGFiZWw6IEFsdGVybmF0aXZlcyBjb25zaWRlcmVkCiAgICAgIGRlc2NyaXB0aW9uOiBPcHRpb25hbCBhbHRlcm5hdGl2ZSBhcHByb2FjaGVzIG9yIHdvcmthcm91bmRzLgo="
Write-B64 ".github/ISSUE_TEMPLATE/config.yml" "YmxhbmtfaXNzdWVzX2VuYWJsZWQ6IGZhbHNlCmNvbnRhY3RfbGlua3M6CiAgLSBuYW1lOiBVc2FnZSBhbmQgc2V0dXAgaGVscAogICAgdXJsOiBodHRwczovL2dpdGh1Yi5jb20vYWpheWR1ZGhhbWwwMS1hcmNoL2hpbmF0YS1ib3QvYmxvYi9tYWluL1NVUFBPUlQubWQKICAgIGFib3V0OiBSZWFkIHRoZSBzdXBwb3J0IGd1aWRlIGJlZm9yZSBvcGVuaW5nIGFuIGlzc3VlLgo="
Write-B64 ".editorconfig" "cm9vdCA9IHRydWUKClsqXQpjaGFyc2V0ID0gdXRmLTgKZW5kX29mX2xpbmUgPSBsZgppbnNlcnRfZmluYWxfbmV3bGluZSA9IHRydWUKaW5kZW50X3N0eWxlID0gc3BhY2UKaW5kZW50X3NpemUgPSAyCgpbKi5tZF0KdHJpbV90cmFpbGluZ193aGl0ZXNwYWNlID0gZmFsc2UK"
Write-B64 "data/.gitkeep" ""

# Keep the user's real local config/data, but stop tracking them publicly.
git ls-files --error-unmatch config.json *> $null
if ($LASTEXITCODE -eq 0) {
  git rm --cached -- config.json | Out-Host
}

git ls-files --error-unmatch data/levels.json *> $null
if ($LASTEXITCODE -eq 0) {
  git rm --cached -- data/levels.json | Out-Host
}

Say "Checking for obviously dangerous tracked secret filenames..."
$tracked = @(git ls-files)
$badTracked = $tracked | Where-Object { $_ -match '(^|/)(\.env|id_rsa|.*\.pem|.*\.p12|.*\.key)$' -and $_ -ne ".env.example" }
if ($badTracked.Count -gt 0) {
  Write-Host "WARNING: review these tracked files before pushing:" -ForegroundColor Red
  $badTracked | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
}

if (Get-Command npm -ErrorAction SilentlyContinue) {
  Say "Generating package-lock.json..."
  npm install --package-lock-only
  if ($LASTEXITCODE -ne 0) {
    throw "npm could not generate package-lock.json."
  }

  Say "Running syntax check..."
  npm run check
  if ($LASTEXITCODE -ne 0) {
    throw "Syntax check failed. No commit was made."
  }

  Say "Running tests..."
  npm test
  if ($LASTEXITCODE -ne 0) {
    throw "Tests failed. No commit was made."
  }
} else {
  Write-Host "npm was not found. Files were prepared, but package-lock/tests were skipped." -ForegroundColor Yellow
}

Say "Staging changes..."
git add -A

Write-Host ""
git status --short | Out-Host
Write-Host ""

if (-not $NoCommit) {
  $answer = Read-Host "Commit the OSS upgrade now? [Y/n]"
  if ([string]::IsNullOrWhiteSpace($answer) -or $answer -match '^[Yy]') {
    git commit -m "chore: prepare Hinata for open-source development"
    if ($LASTEXITCODE -ne 0) {
      throw "Git commit failed."
    }
    Say "Commit created."

    if (-not $NoPush) {
      $push = Read-Host "Push the commit to GitHub now? [Y/n]"
      if ([string]::IsNullOrWhiteSpace($push) -or $push -match '^[Yy]') {
        git push origin main
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Push failed. Your commit is safe locally; push later from GitHub Desktop." -ForegroundColor Yellow
        } else {
          Say "Pushed to GitHub."
        }
      }
    }
  }
}

# Update repo metadata when GitHub CLI is already installed and authenticated.
if (Get-Command gh -ErrorAction SilentlyContinue) {
  gh auth status *> $null
  if ($LASTEXITCODE -eq 0) {
    Say "Updating repository description/topics with GitHub CLI..."
    gh repo edit ajaydudhaml01-arch/hinata-bot `
      --description "Modular open-source Discord.js bot for moderation, tickets, leveling, dynamic voice channels, self-roles, and community utilities." `
      --add-topic discord-bot `
      --add-topic discord-js `
      --add-topic moderation `
      --add-topic tickets `
      --add-topic leveling `
      --add-topic self-hosted *> $null
  }
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " Hinata OSS upgrade finished." -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next: check the GitHub Actions CI run. Once it is green, create the first release/tag." -ForegroundColor White
Write-Host "Backup: $backup" -ForegroundColor DarkGray
